# -*- coding: utf-8 -*-
"""Test3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KP4KHSiHvz0I3souObV4Xy-w1BRssvdh
"""

import pandas as pd
df = pd.read_excel("flipkart_sales_data (1).xlsx")
df.head()

df.info()

df.isnull().sum()

num_cols = ["Sales Amount","Quantity Sold","Customer Rating","Discount (%)"]
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

df.isnull().sum()

cat_cols = ["Product Category", "Region", "Payment Method"]
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

df["Order Date"] = df["Order Date"].fillna(df["Order Date"].mode()[0])
df["Order Date"] = pd.to_datetime(df["Order Date"])

df.isnull().sum()

# upto above process we r filling all the missing
#values for both...categorical & numerical columns
# soo Handling missing values is cmpltd

# Fixing incorrect data types or formats

df.dtypes

num_cols = ["Sales Amount","Quantity Sold","Customer Rating","Discount (%)"]
for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df["Quantity Sold"] = df["Quantity Sold"].astype(int)

cat_cols = ["Product Category","Region","Payment Method"]
for col in cat_cols:
    df[col] = df[col].str.strip()

df.columns = df.columns.str.replace(" ", "_")
df.columns = df.columns.str.replace("(", "")
df.columns = df.columns.str.replace(")", "")
df.columns = df.columns.str.replace("%", "Percent")

df.dtypes

#Fixing Incorrect Data Type COMPLETED

#Detecting and treating outliers

num_cols = ["Sales_Amount", "Quantity_Sold", "Customer_Rating", "Discount_Percent"]
for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower) | (df[col] > upper)]
    print(f"{col} → Outliers: {outliers.shape[0]}")

#Detecting and treating outliers  completed
#Removing duplicate records  started below

df.duplicated().sum()

#Data Preprocessing (Step-by-Step) is completed upto here

#Categorical Variable Handling
#One-Hot Encoding

df_onehot = pd.get_dummies(df, columns=["Product_Category"], drop_first=True)
df_onehot.to_csv("onehot_encoded.csv", index=False)

# Label Encoding
df_label = df.copy()
le = LabelEncoder()
df_label["Payment_Method_Label"] = le.fit_transform(df_label["Payment_Method"])
df_label.to_csv("label_encoded.csv", index=False)

#Ordinal Encoding-
df_ordinal = df.copy()
df_ordinal["Rating_Category"] = pd.cut(
    df_ordinal["Customer_Rating"],
    bins=[0, 2.5, 4, 5],
    labels=["Low", "Medium", "High"]
)
ordinal_encoder = OrdinalEncoder(categories=[["Low", "Medium", "High"]])
df_ordinal["Rating_Encoded"] = ordinal_encoder.fit_transform(df_ordinal[["Rating_Category"]])
df_ordinal.to_csv("ordinal_encoded.csv", index=False)

#Frequency Encoding
df_freq = df.copy()
freq_map = df_freq["Region"].value_counts()
df_freq["Region_Frequency"] = df_freq["Region"].map(freq_map)
df_freq.to_csv("frequency_encoded.csv", index=False)

# target encoding
df_target = df.copy()
target_mean = df_target.groupby("Region")["Sales_Amount"].mean()
df_target["Region_Target_Encoded"] = df_target["Region"].map(target_mean)
df_target.to_csv("target_encoded.csv", index=False)

# . Categorical Variable Handling completed
# feature scaling is started below

# min max scaling
from sklearn.preprocessing import MinMaxScaler
df_minmax = df.copy()
minmax_scaler = MinMaxScaler()
df_minmax[num_cols] = minmax_scaler.fit_transform(df_minmax[num_cols])
df_minmax.head()

# max absolute scaling
from sklearn.preprocessing import MaxAbsScaler
df_maxabs = df.copy()
maxabs_scaler = MaxAbsScaler()
df_maxabs[num_cols] = maxabs_scaler.fit_transform(df_maxabs[num_cols])
df_maxabs.head()

#Vector normalization
from sklearn.preprocessing import Normalizer
df_normalized = df.copy()
normalizer = Normalizer()
df_normalized[num_cols] = normalizer.fit_transform(df_normalized[num_cols])
df_normalized.head()

#Z=score standardization
from sklearn.preprocessing import StandardScaler
df_standard = df.copy()
standard_scaler = StandardScaler()
df_standard[num_cols] = standard_scaler.fit_transform(df_standard[num_cols])
df_standard.head()

# train & test dataa
from sklearn.model_selection import train_test_split
# Define target
y = df["Sales_Amount"]
X = df.drop("Sales_Amount", axis=1)
# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)
print("Training set size:", X_train.shape)
print("Testing set size:", X_test.shape)