# -*- coding: utf-8 -*-
"""Ml_models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hNtDN9LCekk9AaczWQbLpXCCOkUjd2Qu
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import pandas as pd
df = pd.read_csv("Blinkit.csv")
df.head()

# Handling Missing Values

# Check missing values
df.isnull().sum()
# Fill numerical column missing values with mean
df["Item Weight"] = df["Item Weight"].fillna(df["Item Weight"].mean())
# Fill categorical column missing values with mode
df["Outlet Size"] = df["Outlet Size"].fillna(df["Outlet Size"].mode()[0])

#Fixing Wrong Data Types
# Check data types
df.info()
# Example: convert categorical columns to category type
categorical_cols = ["Item Fat Content","Item Type","Outlet Size",
                    "Outlet Location Type","Outlet Type"]
for col in categorical_cols:
    df[col] = df[col].astype("category")

#Detecting and Treating Outliers
# Boxplot to detect outliers
plt.figure(figsize=(6,4))
sns.boxplot(x=df["Sales"])
plt.title("Outliers in Sales")
plt.show()

#Removing Duplicate Records
df.duplicated().sum()
df = df.drop_duplicates()

#Removing Irrelevant features
df = df.drop(["Item Identifier","Outlet Identifier"], axis=1)

#Handling Categorical Variables (Encoding)
df = pd.get_dummies(df, drop_first=True)

#Transforming Skewed Features
df.skew()
df["Sales"] = np.log1p(df["Sales"])

#Splitting Data into Features and Target
X = df.drop("Sales", axis=1)
y = df["Sales"]

#Splitting into Training and Testing Sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

#Applying Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#Importing libraries for ml models
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

#Evaluation / Regression Metrics
def evaluate_model(y_test, y_pred, model_name):
    r2 = r2_score(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_test, y_pred)

    print("\n",model_name,"Results")
    print("R2 Score:", r2)
    print("MSE:", mse)
    print("RMSE:", rmse)
    print("MAE:", mae)

# Linear Regression
#Trained
lr = LinearRegression()
lr.fit(X_train, y_train)
# prediction
y_pred_lr = lr.predict(X_test)
#evaluate
evaluate_model(y_test, y_pred_lr, "Linear Regression")

#Decision Tree Model
#Trained
dt = DecisionTreeRegressor(random_state=42)
dt.fit(X_train, y_train)
# prediction
y_pred_dt = dt.predict(X_test)
#evaluate
evaluate_model(y_test, y_pred_dt, "Decision Tree")

#Random Forest Model
#Trained
rf = RandomForestRegressor(random_state=42)
rf.fit(X_train, y_train)
# prediction
y_pred_rf = rf.predict(X_test)
#evaluate
evaluate_model(y_test, y_pred_rf, "Random Forest")

#Model Performance Comparison
results = pd.DataFrame({

    "Model": ["Linear Regression","Decision Tree","Random Forest"],

    "R2 Score": [
        r2_score(y_test,y_pred_lr),
        r2_score(y_test,y_pred_dt),
        r2_score(y_test,y_pred_rf)
    ],

    "RMSE": [
        np.sqrt(mean_squared_error(y_test,y_pred_lr)),
        np.sqrt(mean_squared_error(y_test,y_pred_dt)),
        np.sqrt(mean_squared_error(y_test,y_pred_rf))
    ]

})

results



